Repository devops-wishlist-buddies/wishlists, pull requests merged in 2021-11, with the labels that each got.

#58 #42 set up GitHub actions
  .github/workflows/workflow.yml
  README.md
Labels: technical debt

#59 change FLASK port to 3000
  README.md
  Vagrantfile
Labels: bug

#62 Add query string support to List function
  service/routes.py
  tests/test_routes.py
  tests/test_wishlist.py
Labels: bug

#63 60 set up codecov
  .coveragerc
  .github/workflows/workflow.yml
  README.md
  setup.cfg
Labels: technical debt

#64 12 deploy to cloud
  Procfile
  README.md
  Vagrantfile
  config.py
  dot-env-exmaple
  manifest.yml
  requirements.txt
  runtime.txt
  service/__init__.py
  service/models/model_utils.py
  service/routes.py
  tests/test_model_utils.py
  tests/test_product.py
  tests/test_routes.py
  tests/test_wishlist.py
Labels: enhancement, technical debt

#67 66 refactor init db for less connections
  service/models/product.py
  service/models/wishlist.py
  service/routes.py
  tests/test_model_utils.py
  tests/test_product.py
  tests/test_routes.py
  tests/test_wishlist.py
Labels: bug

#70 refactor delete logic
  service/routes.py
  tests/test_routes.py
Labels: bug

#90 set up BDD skeleton tests
  features/environment.py
  features/steps/web_steps.py
  features/steps/wishlits_steps.py
  features/wishlists.feature
Labels: enhancement
