Repository devops-wishlist-buddies/wishlists, pull requests merged in 2021-12, with the labels that each got.

#123 refactor logic related to products
  manifest.yml
  service/routes.py
  service/static/js/index.js
  tests/test_routes.py
Labels: enhancement

#125 refactor add to cart
  service/routes.py
Labels: enhancement

#126 fixed 500 in rename
  service/error_handlers.py
  service/routes.py
  tests/test_routes.py
Labels: bug

#127 105 Updated ui and behave tests
  features/steps/web_steps.py
  features/wishlists.feature
  service/models/product.py
  service/static/assets/favicon.png
  service/static/css/index.css
  service/static/index.html
  service/static/js/index.js
  tests/factories.py
  tests/test_product.py
  tests/test_routes.py
Labels: enhancement

#128 fixed 500 in rename
  service/routes.py
Labels: bug

#139 rollback db when failed
  service/__init__.py
  service/error_handlers.py
  service/models/model_utils.py
  service/models/product.py
  service/models/wishlist.py
  service/routes.py
  tests/test_product.py
  tests/test_routes.py
  tests/test_wishlist.py
Labels: bug

#140 improved tdd cover
  service/routes.py
  tests/test_routes.py
Labels: bug

#144 Update routes.py
  service/routes.py
Labels: technical debt

#141 Added string length check
  features/wishlists.feature
  service/static/index.html
Labels: bug
